taskList_Django/urls.py
from django.contrib import admin
from django.urls import path
from taskApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('singup/', views.singup, name='singup'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks_completed/', views.tasksCompleted, name='tasksCompleted'),
    path('logout/', views.log_out, name='logout'),
    path('login/', views.singin, name='login'),
    path('createTask/', views.createTask, name='createTask'),
    path('tasks/<int:task_id>/', views.taskDetail, name='detailTask'),
    path('tasks/<int:task_id>/completed', views.completeTask, name='completeTask'),
    path('tasks/<int:task_id>/deleted', views.deleteTask, name='deleteTask'),
]

taskApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class  Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    dateCompleted = models.DateTimeField(null=True, blank=True)
    priority = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title + " - " + self.user.username

taskApp/forms.py
from django.forms import ModelForm
from .models import Task
# Para crear un form personalizado, debemos crear dentro de nuestra app un archivo form.py y dentro de el ponemos el modelo en el cual se va a basar para realizar el form

class CreateTask(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'priority']

taskApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
# crear y autenticar usuarios
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
# crea una cookie de autenticacion
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
# importamos el formulario para pasarlo el template de create.html
from .forms import CreateTask
from .models import Task
from django.utils import timezone
from django.contrib.auth.decorators import login_required


def home(request):
    return render(request, 'home.html')


def singup(request):

    if request.method == 'GET':
        return render(request, 'singup.html', {
            'form': UserCreationForm
        })

    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(
                    username=request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('tasks')
            except IntegrityError:
                return render(request, 'singup.html', {
                    'form': UserCreationForm,
                    'error': "user already exist"
                })
        else:
            return render(request, 'singup.html', {
                'form': UserCreationForm,
                'error': "password invalid"
            })

@login_required
def tasks(request):
    # traemos solo las tareas del usuario en sesion
    tasks = Task.objects.filter(user=request.user, dateCompleted__isnull=True)
    if tasks.exists():
        # Si hay tareas, las mostramos
        return render(request, 'tasks.html', {
            'tasks': tasks
        })
    else:
        # Si no hay tareas, mostramos un mensaje
        message = "No hay tareas aún"
        return render(request, 'tasks.html', {
            'message': message
        })

@login_required   
def tasksCompleted(request):
    # traemos solo las tareas del usuario en sesion
    tasks = Task.objects.filter(user=request.user, dateCompleted__isnull=False).order_by('-dateCompleted')
    if tasks.exists():
        # Si hay tareas, las mostramos
        return render(request, 'tasks/completed.html', {
            'tasks': tasks
        })
    else:
        # Si no hay tareas, mostramos un mensaje
        message = "No hay tareas completadas"
        return render(request, 'tasks/completed.html', {
            'message': message
        })

@login_required
def log_out(request):
    logout(request)
    return redirect('home')


def singin(request):
    if request.method == 'GET':
        return render(request, 'login.html', {
            'form': AuthenticationForm
        })
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        print(request.POST)
        if user is None:
            return render(request, 'login.html', {
                'form': AuthenticationForm,
                'error': "username or password is incorrect"
            })
        else:
            # guardamos la sesion del usuario con la cookie
            login(request, user)
            return redirect('home')

@login_required
def createTask(request):
    if request.method == 'GET':
        return render(request, 'tasks/create.html', {
            'createForm': CreateTask
        })
    else:
        try:
            data = CreateTask(request.POST)
            new_task = data.save(commit=False)
            new_task.user = request.user
            new_task.save()
            return redirect('tasks')
        except ValueError:
            return render(request, 'tasks/create.html', {
                'createForm': CreateTask,
                'error': 'Datos invalidos'
            })

@login_required
def taskDetail(request, task_id):
    if request.method == 'GET':
        task = get_object_or_404(Task, pk=task_id, user=request.user) 
        form = CreateTask(instance=task)
        return render(request,'tasks/detail.html',{
            'task': task,
            'form': form
        })
    else:
        try:
            task = get_object_or_404(Task, pk=task_id, user=request.user)
            newForm = CreateTask(request.POST, instance=task)
            newForm.save()
            return redirect('tasks')
        except ValueError:
            return render(request,'tasks/detail.html',{
            'task': task,
            'form': form,
            'error': "No se pudo editar la tarea"
        })

@login_required
def completeTask(request, task_id):
    task = get_object_or_404(Task, pk=task_id, user=request.user )
    if request.method == 'POST':
        task.dateCompleted = timezone.now()
        task.save()
        return redirect('tasks')
    
@login_required
def deleteTask(request, task_id):
    task = get_object_or_404(Task, pk=task_id, user=request.user )
    if request.method == 'POST':
        task.delete()
        return redirect('tasks')

taskApp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href={% static 'styles.css' %}>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Task App</title>
  </head>
  <body>
    <header>
      <div class="nav">
        <input type="checkbox" id="nav-check" />

        <div class="nav-header">
          <div class="nav-title">Task App</div>
        </div>

        <div class="nav-btn" data-toggle="collapse" data-target="#cards" onclick="toggleTarjeta()">
          <label for="nav-check">
            <span></span>
            <span></span>
            <span></span>
          </label>
        </div>
        
        <script>
          function toggleTarjeta() {
            var tarjeta = document.getElementById("cards");
            if (tarjeta.classList.contains("d-block")) {
              tarjeta.classList.remove("d-block");
              tarjeta.classList.add("d-none");
            } else {
              tarjeta.classList.remove("d-none");
              tarjeta.classList.add("d-block");
            }
          }
        </script>

        <div class="nav-links">
          <a href="{% url 'home' %}">Inicio</a>

          {% if user.is_authenticated %}

          <a href="/tasks">Tareas Pendientes</a>

          <a href="{% url 'tasksCompleted' %}">Tareas Completadas</a>

          <a href="/logout">Logout</a>

          {% else %}

          <a href="/singup">SingUp</a>

          <a href="/login">Login</a>

          {% endif %}
        </div>
      </div>
    </header>
    {% block content %} {% endblock content %}
  </body>
</html>

taskApp/templates/home.html
{% extends 'base.html' %}

{% block content %}
<main class="container py-5">
    <section class="card d-block" id="cards">
        <div class="text-center">
            <img src="https://i.ibb.co/k2nC25X/3.jpg" alt="imagen" width="50%">
        </div>
        {% if user.is_authenticated %}
            {% if user.username == "Wilson" or user.username == "Gustavo"%}
                <h2 class="text-center">Hola, {{user.username}} SAPA</h2>
                {% else %}
                <h2 class="text-center">Hola, {{user.username}}</h2>
            {% endif %}
        {% endif %}
        <div class="text-center mb-3">
            <a href="/tasks" class="btn btn-primary">Ver Tareas</a>
        </div>
    </section>
</main>

    
{% endblock content %}

taskApp/templates/login.html
{% extends 'base.html' %}

{% block content %}


<main class="container">
    <section class="card d-block mt-5" id="cards">
      <div class="row">
        <div class="col-md-6 offset-md-4">
          <form action="/login/" method="POST" class="text-center">
            <h1 class="mb-3 col-sm-9">Iniciar Sesion</h1>
            {{error}} 
            {% csrf_token %}
  
            <div class="mb-3 col-sm-9">
              <label for="username">Username:</label>
              <input type="text" name="username" class="form-control" id="username" placeholder="Ingresa tu usuario">
            </div>
  
            <div class="mb-3 col-sm-9">
              <label for="password">Password:</label>
              <input type="password" name="password" class="form-control" id="password" placeholder="Ingresa tu contraseña">
            </div>
  
            
            <div class="text-center mb-3 col-sm-9">
              <button class="btn btn-dark">Login</button>
            </div>
          </form>
          
        </div>
      </div>
    </section>
  </main>

{% endblock content %}

taskApp/templates/singup.html
{% extends 'base.html' %}

{% block content %}

<main class="container">
  <section class="card d-block mt-5" id="cards">
    <div class="row">
      <div class="col-md-6 offset-md-4">
        <form action="" method="POST" class="text-center">
          <h1 class="mb-3 col-sm-9">Registrarse</h1>
          {{error}} 
          {% csrf_token %}

          <div class="mb-3 col-sm-9">
            <label for="username">Username:</label>
            <input type="text" name="username" class="form-control" id="username" placeholder="Ingresa tu usuario">
          </div>

          <div class="mb-3 col-sm-9">
            <label for="password1">Password:</label>
            <input type="password" name="password1" class="form-control" id="password1" placeholder="Ingresa tu contraseña">
          </div>

          <div class="mb-3 col-sm-9">
            <label for="password2">Confirm your Password:</label>
            <input type="password" name="password2" class="form-control" id="password2" placeholder="Verificar contraseña">
          </div>
          
          <div class="text-center mb-3 col-sm-9">
            <button class="btn btn-dark">Sing Up</button>
          </div>
        </form>
        <div class="text-center mb-3 col-sm-9">
          <a href="/login" class="btn btn-primary">¿Ya tienes una cuenta?</a>
        </div>
      </div>
    </div>
  </section>
</main>

{% endblock content %}

taskApp/templates/tasks.html
{% extends 'base.html' %} 

{% block content %}

<main class="container">
  <section class="card d-block mt-5" id="cards">
    <div class="row">
      <div class="col-md-6 offset-md-4">
        <h1 class="text-center mb-3 col-sm-9">Tareas Pendientes</h1>
        {{message}} 
        
        {% for task in tasks%}
            <ul>
            <li>
                <a href="{% url 'detailTask' task.id %}">
                <h3 class="text-center mb-3 col-sm-9">{{task.title}}</h3>
                </a>
                <p class="text-center mb-3 col-sm-9">{{task.description}}</p>
            </li>
            </ul>
        {% endfor %}
        <div class="text-center mb-3 col-sm-9">
          <a href="/createTask/" class="btn btn-info">Nueva Tarea</a>
        </div>
      </div>
    </div>
  </section>
</main>

{% endblock content %}

taskApp/templates/tasks/completed.html
{% extends 'base.html' %}

{% block content %}
    <main class="container">
        <section class="card d-block mt-5" id="cards">
            <div class="row">
                <div class="col-md-6 offset-md-4">
                    <h1 class="text-center mb-3 col-sm-9">Tareas Completadas</h1>
                    {{message}}
                    {% for task in tasks%}
                        <ul class="list-group">
                            <li class="">
                                <h2 class="text-center mb-3 col-sm-9">{{task.title}}</h2>
                                <p class="text-center mb-3 col-sm-9">{{task.description}}</p>
                                <h4 class="text-center mb-3 col-sm-9">Completada:</h4>
                                <p class="text-center mb-3 col-sm-9">{{task.dateCompleted}}</p>
                            </li>
                        </ul>
                    {% endfor %}
                    <div class="text-center mb-3 col-sm-9">
                        <a href="/createTask/" class="btn btn-info">Nueva Tarea</a>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock content %}

taskApp/templates/tasks/create.html
{% extends 'base.html' %} 

{% block content %}
    <main class="container">
        <section class="card d-block mt-5" id="cards">
          <div class="row">
            <div class="col-md-6 offset-md-4">
              <form action="/createTask/" method="POST" class="text-center">
                <h1 class="mb-3 col-sm-9">Crear nueva Tarea</h1>
                {{error}} 
                {% csrf_token %}
      
                <div class="mb-3 col-sm-9">
                  <label for="id_title">Titulo:</label>
                  <input class="form-control" type="text" name="title" maxlength="100" id="id_title" required>
                </div>
      
                <div class="mb-3 col-sm-9">
                    <label for="id_description">Descripcion:</label>
                    <textarea name="description" cols="40" rows="10" id="id_description"></textarea>
                  </div>
      
                <div class="mb-3 col-sm-9">
                  <label for="id_priority">Priority:</label>
                  <input type="checkbox" name="priority" id="id_priority" checked="">
                </div>

                
                <div class="text-center mb-3 col-sm-9">
                  <button class="btn btn-success">Guardar</button>
                </div>
              </form>
            </div>
          </div>
        </section>
      </main>
      

{% endblock content %}

taskApp/templates/tasks/detail.html
{% extends 'base.html' %} 

{% block content %}
    
    <main class="container">
        <section class="card d-block mt-5" id="cards">
          <div class="row">
            <div class="col-md-6 offset-md-4">
              <h2 class="text-center mb-3 col-sm-9">{{task.title}}</h2>
              {{error}} 
              <form method="POST" class="text-center">
                {% csrf_token %}
                <div class="mb-3 col-sm-9">
                  <label for="id_title">Titulo:</label>
                  <input class="form-control" type="text" name="title" maxlength="100" id="id_title" value="{{task.title}}" required>
                </div>
      
                <div class="mb-3 col-sm-9">
                    <label for="id_description">Descripcion:</label>
                    <textarea name="description" cols="40" rows="10" id="id_description">{{task.description}}</textarea>
                  </div>
      
                <div class="mb-3 col-sm-9">
                  <label for="id_priority">Priority:</label>
                  <input type="checkbox" name="priority" id="id_priority" checked="">
                </div>
                <div class="text-center mb-3 col-sm-9">
                  <button class="btn btn-primary">Editar</button>
                </div>
              </form>

              <div class="text-center mb-3 col-sm-9">
                  <form action="{% url 'completeTask' task.id %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-success">Completada</button>
                </form>
              </div>

              <div class="text-center mb-3 col-sm-9">
                <form action="{% url 'deleteTask' task.id %}" method="POST">
                  {% csrf_token %}
                  <button class="btn btn-danger">Borrar</button>
              </form>
            </div>
              
            </div>
          </div>
        </section>
      </main>
    

{% endblock content %}